#Basic Numpy

##Numpy stands for numerical python

####The starring role is played by the "ndarray"
####The numpy library also provides linear algebra routines
####Pandas is built on numpy
####There is overlap in what numpy provides, in terms of data analysis capabilities

In [2]:
#The standard way to import the numpy library
import numpy as np

#Constructing

In [4]:
#TODO create a python list to hold the following numbers 3, 4.7, 2, 0, 1.2, 1
mylist = [3, 4.7, 2, 0, 1.2, 1]
#TODO convert the python list to an ndarry using the "np.array()" method
newarray = np.array(mylist)
print newarray

[ 3.   4.7  2.   0.   1.2  1. ]


In [6]:
#TODO using the shape attribute print out the shape of the ndarray you created
print newarray.shape
#TODO using the dtype attribute print out the type of the ndarray you created
print newarray.dtype

(6,)
float64


In [13]:
#TODO create a second list of numbers 2, 3.4, 3.3, 6, 2, 1
secondlist=[2, 3.4, 3.3, 6, 2, 1]
full=mylist + secondlist
print full
#TODO in python create a new list which contains the 2 lists of numbers
#TODO convert this list of lists into a 2 dimensionl ndarray
fullarray = np.array(full)
#TODO confirm the dimensionality of the array using the ndim attribute, also print out the shape and type
print fullarray.ndim
print fullarray.shape
print fullarray.dtype

[3, 4.7, 2, 0, 1.2, 1, 2, 3.4, 3.3, 6, 2, 1]
1
(12,)
float64


####There are a number of helper functions to create arrays from scratch

In [20]:
#TODO using the np.zeros and np.ones methods create 4 ndarrays, 2 of type int, 2 of type float 
first = np.zeros(2, dtype=float)
second = np.zeros((2, 3), dtype=int)
third = np.ones(2, dtype=float)
fourth = np.ones((2, 3), dtype=int)
#hint: there is a dtype option within the array method that can be used to set the type

####It is often necessary to recast data types from one type to another, as we will see with the upcoming exploratory data analysis work

In [22]:
#TODO using the built in method astype convert one of the numerica arrays into an array of strings
stringfirst = first.astype(str)
#TODO confirm that the new array really is of dtype string
print stringfirst.dtype

|S32


##Question: Does astype create a new copy of the array?

####Often when you read datasets from file numbers get read as strings

In [24]:
#TODO convert the array of strings back to floats
backagain = stringfirst.astype(float)
print backagain.dtype

float64


In [73]:
#TODO what does the np.arange do
#TODO create an integer array containing 20 integers, starting at 50 and going up in steps of 2
test = np.arange (50, 90, 2, dtype=int)
print test.shape
print test

(20,)
[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


#Vectorization

In [41]:
#TODO create a 2 by 3 array of floats - use the array you created above or create new ones
x = np.array(((2, 3), (8,2), (9,1)), dtype=float)

In [45]:
#TODO produce an array of the squares of all the number
print np.square(x)
#TODO produce an array of the sum of all the numbers
print np.sum(x)
#TODO produce an array where all the numbers are multiplied by 4.3
print np.multiply(x, 4.3)

[[  4.   9.]
 [ 64.   4.]
 [ 81.   1.]]
25.0
[[  8.6  12.9]
 [ 34.4   8.6]
 [ 38.7   4.3]]


##Question what is the difference between vectorization and broadcasting

#Basic Indexing, Slicing and Dicing

In [59]:
#TODO using the array of 20 integers you created above find:
#The 5th element
print test
print test[4]
#The 5th to 8th elements inclusive
print test[4:8]

[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]
58
[58 60 62 64]


In [63]:
#TODO multiply the 5th to 8th elements by 5.6
print np.multiply(test[4:8], 5.6)
#TODO now print the original array in full
print test

[ 324.8  336.   347.2  358.4]
[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


##Question: What do you notice about the changes you made to the slice?

In [65]:
#TODO This time make a slice by using the 'copy' method
new = np.copy(test[4:8])
#TODO Multiply this by 0.5
print np.multiply(new, 0.5)
#TODO print the original array
print test

[ 29.  30.  31.  32.]
[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


####This is the difference between a view and a copy

In [74]:
#TODO using the array of 20 integers slice the array from the begining to the 10th element
print test[:9]
#TODO now slice it from the 4th element to the end
print test[3:]
#TODO assign 32 to all the elements of the slice
test[3:] = 32
#TODO print the original array
print test

[50 52 54 56 58 60 62 64 66]
[56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]
[50 52 54 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32]


##Sorting

In [83]:
a = np.array([4, 5, 2, 8, 1])
#TODO using the built in sort method to sort this array
new = np.sort(a, axis=0)
#TODO confirm the array has been sorted by printing out the array
print new

[1 2 4 5 8]


In [95]:
a = np.array([[4, 3, 29], [8, 6, 11]])
#TODO print the shape of this multi-dimensional array
print a.shape
#TODO print the array an sort each row, reprint the array to confirm
print np.sort(a[0])
print np.sort(a[1])
print a
##how do you get this back in without writing a new array?
a = np.array([[4, 3, 29], [8, 6, 11]])
print np.sort(a[:,0])
print np.sort (a[:,1])
print np.sort (a[:,2])
#TODO now sort by columns

(2, 3)
[ 3  4 29]
[ 6  8 11]
[[ 4  3 29]
 [ 8  6 11]]
[4 8]
[3 6]
[11 29]


##NP arrays as sets

In [96]:
names = np.array(['Jim', 'John', 'Bill', 'Tony', 'Jim', 'Bill', 'Daniel', 'Jim'])
#TODO print out just the unique names in this nd array
print np.unique(names)

['Bill' 'Daniel' 'Jim' 'John' 'Tony']


#Random Number Generation

Here is a linkg to the documentation for the random sampling routines built into numpy http://docs.scipy.org/doc/numpy/reference/routines.random.html#

These are incredibly useful and powerful

In [99]:
#TODO using np.random.rand create an array of 10 random numbers
randomness = np.random.rand(10)
print randomness

[ 0.37898112  0.05516023  0.82080338  0.38682452  0.51022774  0.10394848
  0.58762998  0.3127031   0.41741468  0.58627843]


#Universal Functions

####A function that performs elementwise operation on the data in an nddarray.

In [101]:
#TODO using the random number array you created above caluclate the following for all the elements of the array:
#the square root
print np.sqrt(randomness)
#the absolute value
print np.abs(randomness)

[ 0.61561443  0.23486215  0.905982    0.62195218  0.71430227  0.32241041
  0.76657027  0.55919862  0.64607637  0.76568821]
[ 0.37898112  0.05516023  0.82080338  0.38682452  0.51022774  0.10394848
  0.58762998  0.3127031   0.41741468  0.58627843]


In [107]:
#TOD create a boolean array by checking that each element of the array is "not a number
boolean = np.isnan(randomness)
print boolean

[False False False False False False False False False False]


##Mathematical and Statistical Methods

In [117]:
#TODO create an array of 1000 normally distributed numbers (standard normal distribution)
normalness = np.random.normal(0, 10, 1000)

In [122]:
#TODO get the mean, sum, standard deviation, and cumulative sum
print np.mean(normalness)
print np.sum(normalness)
print np.std(normalness)
print np.cumsum(normalness)

-0.179277745951
-179.277745951
9.84567842915
[ -1.31282064e+01  -4.30952397e+00  -9.89371343e+00   6.20007668e+00
   9.38179486e+00   1.70277194e+01   3.08874838e+01   5.28291840e+01
   6.23531468e+01   6.49975437e+01   6.92522495e+01   7.32272545e+01
   6.43704494e+01   5.82388523e+01   5.22697497e+01   6.01749021e+01
   6.74613025e+01   8.02632706e+01   6.59225994e+01   6.89717384e+01
   6.12142625e+01   6.15087674e+01   5.70354671e+01   5.73819720e+01
   6.86989452e+01   6.80908231e+01   5.45447495e+01   6.78589834e+01
   6.87413331e+01   5.80929094e+01   5.62202448e+01   5.83825106e+01
   7.17598856e+01   7.14390983e+01   7.82443961e+01   7.26791017e+01
   8.30888617e+01   8.94222395e+01   9.24611325e+01   6.85190667e+01
   6.77910406e+01   7.95936922e+01   8.46825316e+01   8.86857442e+01
   7.17126538e+01   8.05486284e+01   9.00816306e+01   9.52294891e+01
   9.00143976e+01   8.66381218e+01   8.93704748e+01   9.26423618e+01
   1.01108647e+02   1.23454894e+02   1.05726458e+02   1.14

In [ ]:
##Question: To calculate standard deviation does np.std() use 1/N or 1/(N-1)
1/N

In [125]:
#TODO write no more than 4 lines of code to justify your answer
print np.std(normalness)
print np.std(normalness, ddof=1)

9.84567842915
9.85060496357


##Meshgrid

In [78]:
points = np.arange(-1, 2, 1)
print "points is an array of  ", len(points), "points:", points

#To create a meshgrid we would therefore need a total of 9 points in a grid, 3 along an x axis and 3 along a y axis
x, y = np.meshgrid(points, points)

print "the x axis points are\n", x
print "the y axis points are\n", y

print "The individual pairs of points could be generated like this:"

for i in np.arange(len(points)):
    for j in np.arange(len(points)):
        print "(", x[i][j], ",", y[i][j], ")",

points is an array of   3 points: [-1  0  1]
the x axis points are
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
the y axis points are
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]
The individual pairs of points could be generated like this:
( -1 , -1 ) ( 0 , -1 ) ( 1 , -1 ) ( -1 , 0 ) ( 0 , 0 ) ( 1 , 0 ) ( -1 , 1 ) ( 0 , 1 ) ( 1 , 1 )


####Meshgrad is useful for 3d plotting